name 'chkrootkit'
maintainer 'Briana Sanchez'
maintainer_email 'jokebed23@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures chkrootkit'
long_description 'Installs/Configures chkrootkit'
version '0.1.0'
