# Generated by Chef for <%= node[:fqdn] %>
# Local modifications will be overwritten.

#Declaring variables
CHKROOTKIT_PATH=<%=node['chkrootkit']['installation_directory']%>
CHKROOTKIT_LOG_FILE=<%=node['chkrootkit']['log_file']%>
CHKROOTKIT_DETECTION_FILE=<%=node['chkrootkit']['detection_file']%>
NOTIFICATION_EMAIL=<%=node['chkrootkit']['notification_email']%>
DETECTIONS_LOG=<%=node['chkrootkit']['detections_history_log']%>
INFECTED_FLAG=<%=node['chkrootkit']['infected_flag']%>
READONLY_FS=<%=node['chkrootkit']['read_only_fs']%>
TIMESTAMP=$(date +%F-%T)

#Running chkrootkit script
$CHKROOTKIT_PATH/chkrootkit -p $READONLY_FS &> $CHKROOTKIT_LOG_FILE
if [[ $? -ne 0 ]]; then
  echo -e "$TIMESTAMP \t### AN ERROR OCCURED. CHECK LOGS IN $CHKROOTKIT_LOG_FILE ###"
fi

#Parsing log file
while read -r LINE
do
  if [[ $LINE == *"INFECTED"* ]] || [[ $LINE == *"Vulnerable but disabled"* ]]; then 
    INFECTED_FLAG='true'
    echo -e "$TIMESTAMP \t### VULNERABILITES FOUND ###" | tee -a $CHKROOTKIT_DETECTION_FILE
    echo -e "\t\t\t--> AFFECTED SERVER: $HOSTNAME" | tee -a $CHKROOTKIT_DETECTION_FILE
    echo -e "\t\t\t--> VULNERABILITY: `echo $LINE`" | tee -a $CHKROOTKIT_DETECTION_FILE
    continue # Skip the rest of this particular loop iteration
  fi
  if [[ $INFECTED_FLAG == 'true' ]];then
    if [[ $LINE == *"Searching"* ]] || [[ $LINE == *"Checking"* ]]; then
      echo -e "\t\t\t--> ACTIONS: Sending notification to $NOTIFICATION_EMAIL" | tee -a $CHKROOTKIT_DETECTION_FILE
      mail -s "CHKROOTKIT: Vulnerabilities found on $HOSTNAME" $NOTIFICATION_EMAIL < $CHKROOTKIT_DETECTION_FILE
      INFECTED_FLAG='false'
      cat $CHKROOTKIT_DETECTION_FILE >> $DETECTIONS_LOG
      rm -f $CHKROOTKIT_DETECTION_FILE
      break
    else
      echo -e "\t\t\t\t\t\t $LINE" | tee -a $CHKROOTKIT_DETECTION_FILE
    fi
  fi
done < "$CHKROOTKIT_LOG_FILE"
